"use client";
import Link from "next/link";
import { useState } from "react";

export default function NewServiceForm() {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [createdId, setCreatedId] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form.entries()); const response = await fetch("/api/admin/service-records", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); setBusy(false); if (!response.ok) { setError(result.error || "No se pudo guardar."); return; } setCreatedId(result.publicId); }
  if (createdId) return <div className="card mt-8 max-w-3xl"><h2 className="text-2xl font-bold">Servicio creado correctamente</h2><p className="muted mt-3">Comparte este ID con el cliente:</p><p className="my-5 text-3xl font-bold text-sky-300">{createdId}</p><div className="flex gap-3"><Link className="btn" href={`/portal/${createdId}`}>Ver portal</Link><Link className="rounded-lg border border-slate-600 px-4 py-3" href="/admin">Volver al panel</Link></div></div>;
  return <form onSubmit={submit} className="card mt-8 grid gap-4 md:grid-cols-2"><input name="customerName" required placeholder="Nombre del cliente *" className="rounded-lg bg-slate-900 p-3"/><input name="email" type="email" placeholder="Correo" className="rounded-lg bg-slate-900 p-3"/><input name="phone" placeholder="Teléfono" className="rounded-lg bg-slate-900 p-3"/><input name="make" required placeholder="Marca *" className="rounded-lg bg-slate-900 p-3"/><input name="model" required placeholder="Modelo *" className="rounded-lg bg-slate-900 p-3"/><input name="year" required type="number" placeholder="Año *" className="rounded-lg bg-slate-900 p-3"/><input name="vin" placeholder="VIN" className="rounded-lg bg-slate-900 p-3"/><input name="licensePlate" required placeholder="Placas *" className="rounded-lg bg-slate-900 p-3"/><input name="price" required type="number" step="0.01" min="0" placeholder="Precio inicial *" className="rounded-lg bg-slate-900 p-3"/><textarea name="concept" required placeholder="Concepto inicial de trabajo *" className="rounded-lg bg-slate-900 p-3 md:col-span-2"/><p className="text-sm text-red-300 md:col-span-2">{error}</p><div className="flex gap-3 md:col-span-2"><Link href="/admin" className="rounded-lg border border-slate-600 px-4 py-3">Regresar</Link><button disabled={busy} className="btn flex-1">{busy ? "Guardando..." : "Generar ID y guardar"}</button></div></form>;
}
